# Generated by Django 2.2.10 on 2020-04-10 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zh', models.CharField(max_length=50, null=True, verbose_name='邮箱')),
                ('mm', models.CharField(max_length=50, null=True, verbose_name='密码')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='发件人身份')),
                ('smtp_server', models.CharField(max_length=50, null=True, verbose_name='SMTP 发件服务器')),
            ],
            options={
                'verbose_name': '基础信息配置',
                'verbose_name_plural': '基础信息配置',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50, null=True, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=50, null=True, verbose_name='账号密码')),
                ('host_type', models.IntegerField(choices=[(0, '临时账号'), (1, '正式账号'), (2, '过期账号')], default=1, verbose_name='账号类型')),
                ('url', models.CharField(max_length=50, null=True, verbose_name='登陆地址')),
                ('capacity', models.IntegerField(help_text='人数上限', null=True)),
                ('level', models.IntegerField(default=1, help_text='默认：1。1：一般会议可申请；2：重要会议申请；3：特殊会议可申请。', verbose_name='主持人级别')),
                ('api_key', models.CharField(max_length=50, null=True, verbose_name='api_key')),
                ('api_secret', models.CharField(max_length=50, null=True, verbose_name='api_secret')),
                ('host_id', models.CharField(max_length=50, null=True, verbose_name='host_id')),
                ('host_password', models.CharField(max_length=10, null=True, verbose_name='主持人密码')),
            ],
            options={
                'verbose_name': '主持人账户',
                'verbose_name_plural': '主持人账户',
            },
        ),
        migrations.CreateModel(
            name='MeetingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(null=True, verbose_name='会议是否申请成功')),
                ('topic', models.CharField(max_length=100, null=True, verbose_name='主题')),
                ('start_time', models.CharField(max_length=50, null=True, verbose_name='开始时间')),
                ('end_time', models.CharField(max_length=50, null=True, verbose_name='结束时间')),
                ('requester', models.CharField(max_length=10, null=True, verbose_name='申请人')),
                ('request_time', models.CharField(max_length=50, null=True, verbose_name='申请时间')),
                ('requester_email', models.CharField(max_length=50, null=True, verbose_name='申请人邮箱')),
                ('people', models.IntegerField(null=True, verbose_name='参会人数')),
                ('people_emails', models.TextField(verbose_name='参会者邮箱')),
                ('room_id', models.CharField(max_length=10, null=True, verbose_name='会议号')),
                ('password', models.CharField(max_length=20, null=True, verbose_name='会议密码')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Host', verbose_name='主持人')),
            ],
            options={
                'verbose_name': '历史会议',
                'verbose_name_plural': '历史会议',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, null=True, verbose_name='主题')),
                ('request_status', models.IntegerField(choices=[(0, '失败'), (1, '成功')], verbose_name='申请状态')),
                ('status', models.IntegerField(choices=[(0, '取消'), (1, '正常')], null=True, verbose_name='会议状态')),
                ('level', models.IntegerField(choices=[(0, '一般会议'), (1, '重要会议'), (2, '特殊会议')], default=0, help_text='默认：一般会议。<br />一般会议：向主持人级别：0，发起会议申请；<br />重要会议：向主持人级别：0，1，发起会议申请；<br />特殊会议：向主持人级别：0，1，2，发起会议申请；<br />', verbose_name='会议级别')),
                ('start_time', models.CharField(max_length=50, null=True, verbose_name='开始时间')),
                ('end_time', models.CharField(max_length=50, null=True, verbose_name='结束时间')),
                ('requester', models.CharField(max_length=10, null=True, verbose_name='申请人')),
                ('request_time', models.CharField(max_length=50, null=True, verbose_name='申请时间')),
                ('requester_email', models.CharField(max_length=50, null=True, verbose_name='申请人邮箱')),
                ('people', models.IntegerField(null=True, verbose_name='参会人数')),
                ('people_emails', models.TextField(null=True, verbose_name='参会人邮箱')),
                ('is_mail_all', models.BooleanField(null=True, verbose_name='是否发送参会信息至所有参会人')),
                ('is_mail_success', models.BooleanField(null=True, verbose_name='是否成功发送邮件')),
                ('room_id', models.CharField(max_length=10, null=True, verbose_name='会议号')),
                ('room_status', models.IntegerField(choices=[(0, '取消'), (1, '正常')], default=1)),
                ('room_password', models.CharField(max_length=20, null=True, verbose_name='会议密码')),
                ('room_is_delete', models.BooleanField(null=True, verbose_name='Room是否已删除')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Host', verbose_name='主持人')),
            ],
            options={
                'verbose_name': '会议信息',
                'verbose_name_plural': '会议信息',
            },
        ),
    ]
