# Generated by Django 2.2.10 on 2020-04-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicsetting',
            options={'verbose_name': '基础信息配置', 'verbose_name_plural': '0 基础信息配置'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '主持人账户', 'verbose_name_plural': '1 主持人账户'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': '会议信息', 'verbose_name_plural': '2 会议信息'},
        ),
        migrations.AddField(
            model_name='host',
            name='remark',
            field=models.CharField(max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='host',
            name='capacity',
            field=models.IntegerField(null=True, verbose_name='人数上限'),
        ),
    ]
