# Generated by Django 2.2.10 on 2020-04-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200410_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
