# Generated by Django 2.2.10 on 2020-04-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200410_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='level',
            field=models.IntegerField(default=1, help_text='默认：1。0:不可申请；1：一般会议可申请；2：重要会议申请；3：特殊会议可申请。', verbose_name='主持人级别'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='request_status',
            field=models.IntegerField(choices=[(1, '成功'), (0, '失败')], verbose_name='申请状态'),
        ),
    ]
