# Generated by Django 2.2.10 on 2020-04-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200410_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicsetting',
            name='delay_time',
            field=models.IntegerField(null=True, verbose_name='可延迟时间（时）'),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='early_time',
            field=models.IntegerField(null=True, verbose_name='可提前时间（时）'),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='it',
            field=models.TextField(help_text='多个邮箱以英文逗号","进行分隔。所有会议通知都会通过邮件发送至管理人员邮箱。', null=True, verbose_name='管理员邮箱'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='room_is_delete',
            field=models.BooleanField(null=True, verbose_name='Room 是否已删除'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='room_status',
            field=models.IntegerField(choices=[(0, '取消'), (1, '正常')], default=1, verbose_name='会议状态'),
        ),
    ]
