# Generated by Django 2.2.10 on 2020-04-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200410_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicsetting',
            name='api_create_url',
            field=models.CharField(help_text='强制结束正在开的会议！谨慎调用。如果不知道有什么用，请勿填写。', max_length=100, null=True, verbose_name='API 结束会议室地址'),
        ),
        migrations.AddField(
            model_name='basicsetting',
            name='api_delete_url',
            field=models.CharField(help_text='删除Zoom后台的会议室，如果会议正在进行，无法删除会议。', max_length=100, null=True, verbose_name='API 删除会议室地址'),
        ),
        migrations.AddField(
            model_name='host',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='简称'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='request_status',
            field=models.IntegerField(choices=[(1, '成功'), (0, '失败')], verbose_name='申请状态'),
        ),
    ]
