# Generated by Django 2.2.10 on 2020-04-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200410_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicsetting',
            name='api_end_url',
            field=models.CharField(help_text='强制结束正在开的会议！谨慎调用。如果不知道有什么用，请勿填写。', max_length=100, null=True, verbose_name='API 结束会议室地址'),
        ),
        migrations.AlterField(
            model_name='basicsetting',
            name='api_create_url',
            field=models.CharField(max_length=100, null=True, verbose_name='API 创建会议室地址'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='request_status',
            field=models.IntegerField(choices=[(0, '失败'), (1, '成功')], verbose_name='申请状态'),
        ),
    ]
