# Generated by Django 2.2.10 on 2020-04-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200410_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='room_status',
        ),
        migrations.AddField(
            model_name='meeting',
            name='real_end_time',
            field=models.CharField(max_length=50, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='real_start_time',
            field=models.CharField(max_length=50, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='level',
            field=models.IntegerField(choices=[(0, '一般会议'), (1, '重要会议'), (2, '特殊会议'), (3, '紧急会议')], default=0, help_text='默认：一般会议。<br />一般会议：向主持人级别：0，发起会议申请；<br />重要会议：向主持人级别：0，1，发起会议申请；<br />特殊会议：向主持人级别：0，1，2，发起会议申请；<br />紧急会议：向主持人级别：0，1，2，3，发起会议申请；<br />', verbose_name='会议级别'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='request_status',
            field=models.IntegerField(choices=[(1, '成功'), (0, '失败')], default=0, null=True, verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(choices=[(0, '待定'), (1, '正常'), (2, '作废/取消/结束')], default=0, null=True, verbose_name='会议状态'),
        ),
        migrations.DeleteModel(
            name='MeetingLog',
        ),
    ]
