# Generated by Django 2.2.10 on 2020-04-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200416_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='real_end_time',
            field=models.DateTimeField(null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='real_start_time',
            field=models.DateTimeField(null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='requester',
            field=models.DateTimeField(null=True, verbose_name='申请人'),
        ),
    ]
