# Generated by Django 2.2.10 on 2020-04-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200416_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='real_end_time',
            field=models.DateTimeField(null=True, verbose_name='实际结束时间'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='real_start_time',
            field=models.DateTimeField(null=True, verbose_name='实际开始时间'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='开始时间'),
        ),
    ]
