# Generated by Django 2.2.10 on 2020-04-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200416_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='is_mail_all',
            field=models.BooleanField(default=False, verbose_name='是否发送参会信息至所有参会人'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_mail_success',
            field=models.BooleanField(default=False, verbose_name='是否成功发送邮件'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='request_time',
            field=models.DateTimeField(null=True, verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='requester',
            field=models.CharField(max_length=50, null=True, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='room_is_delete',
            field=models.BooleanField(default=False, verbose_name='Room 是否已删除'),
        ),
    ]
