# Generated by Django 2.2.10 on 2020-04-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200416_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='host',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Host', to_field='account', verbose_name='主持人'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='request_status',
            field=models.IntegerField(choices=[(0, '失败'), (1, '成功')], default=0, null=True, verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='room_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='会议号'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='room_password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='会议密码'),
        ),
    ]
