# Generated by Django 2.2.10 on 2020-04-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200416_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='ct_meetings',
            field=models.TextField(blank=True, null=True, verbose_name='冲突会议室列表'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='enable_delay_time',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否启用延迟时间'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='enable_early_time',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否启用提前时间'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_mail_all',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否发送会议信息至参会人'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_mail_success',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否成功发送邮件至参会人'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='request_status',
            field=models.IntegerField(choices=[(1, '成功'), (0, '失败')], default=0, null=True, verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='room_is_delete',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否已删除 Room '),
        ),
    ]
