# Generated by Django 2.2.10 on 2020-04-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200416_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='is_mail_success',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否成功发送邮件'),
        ),
    ]
