# Generated by Django 2.2.10 on 2020-04-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200416_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='request_status',
            field=models.IntegerField(choices=[(2, '失败 - 人数超出限制'), (1, '成功'), (0, '失败 - 无可用会议室')], default=0, null=True, verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(choices=[(0, '待定/未获取'), (1, '正常'), (2, '作废/取消'), (3, '结束')], default=0, null=True, verbose_name='会议状态'),
        ),
    ]
